// Thomas Learning Project

#pragma once

#include "NativeGameplayTags.h"

// Vital Attributes
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Health);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_MaxHealth);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Mana);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_MaxMana);

// Primary Attributes
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Strength);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Intelligence);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Resilience);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Vigor);

// Secondary Attributes
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_Armor);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_ArmorPenetration);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_BlockChance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitChance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitDamage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitResistance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_HealthRegeneration);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_ManaRegeneration);

// Resistance Attributes
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Fire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Lightning);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Arcane);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_Physical);

// Damage Types
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Fire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Lightning);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Arcane);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical);

// Event Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_HitReact);

// Character Status Tag
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_Dead);

// Input Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Mouse_LeftButton);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Mouse_RightButton);


// HUDLayout Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUDLayout_Overlay);

// Widget Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Widget_Player);